topcoder-platform/submissions-api

- README.md
- app.js
- config/default.js
- constants.js
- docs/swagger.yaml
- package-lock.json
- package.json
- src/common/dbhelper.js
- src/common/helper.js
- src/models/Review.js
- src/models/ReviewSummation.js
- src/models/ReviewType.js
- src/models/Submission.js
- src/services/SubmissionService.js
> Multiple Enhancements

- app.js
- src/routes/ReviewRoutes.js
- src/routes/ReviewSummationRoutes.js
- src/routes/ReviewTypeRoutes.js
- src/routes/SubmissionRoutes.js
> Check for auth scopes too

- scripts/data/ReviewSummations.json
- scripts/data/Reviews.json
- src/services/ReviewService.js
- src/services/ReviewSummationService.js
- src/services/ReviewTypeService.js
- src/services/SubmissionService.js
- test/common/testData.js
- test/e2e/ReviewService.test.js
- test/e2e/ReviewSummationService.test.js
- test/e2e/ReviewTypeService.test.js
- test/e2e/SubmissionService.test.js
- test/unit/prepare.js
> GET /resource/:resourceId from ES

- docs/swagger.yaml
- src/services/SubmissionService.js
> Fixes for Issue #28

- .dockerignore
- README.md
- docker/Dockerfile
- docker/docker-compose.yml
- docker/sample.api.env
Don't merge yet. Still being reviewed
> Dockerizing the Application

- docs/swagger.yaml
Swagger fixes for POST /submissions
> Swagger fixes

- src/controllers/HealthCheckController.js
- src/routes/HealthCheckRoute.js
- src/routes/index.js
- src/services/HealthCheckService.js
> Add health check

- package-lock.json
- package.json
- src/services/SubmissionService.js
> Validate fileType

- constants.js
- src/services/ReviewService.js
- src/services/ReviewSummationService.js
- src/services/SubmissionService.js
> M2M token handling

- src/common/helper.js
> submissionPhaseId Selection logic

- constants.js
- src/services/ReviewService.js
- src/services/ReviewSummationService.js
- src/services/SubmissionService.js
> Use sub for Machine tokens

- scripts/createIndex.js
- src/common/helper.js
- src/services/SubmissionService.js
> Support for nested filter in Submission service

- .circleci/config.yml
- scripts/createIndex.js
- src/common/helper.js
- src/services/SubmissionService.js
new ES structure to support filters
> prod roll w/ new ES docs

- README.md
- config/default.js
- package.json
- scripts/migrateFromDBToES.js
- src/common/dbhelper.js
> Script to migrate data from DB to ES

- src/services/SubmissionService.js
> Add more log statements to create and update submission

- config/default.js
- package-lock.json
- package.json
- scripts/importData.js
- src/common/helper.js
- src/services/ReviewService.js
- src/services/ReviewSummationService.js
- src/services/ReviewTypeService.js
- src/services/SubmissionService.js
> Use Bus API wrapper to post events to Bus API

- src/common/helper.js
- src/controllers/SubmissionController.js
- src/services/SubmissionService.js
Test data need to be modified to validate different scenarios.
Design challenges seem to have phases like `Checkpoint Screening`, `Checkpoint Review` etc.. which need to be handled.
There are other complicated role checks too.
> WIP: Check for Topcoder User role

- src/common/helper.js
- src/services/SubmissionService.js
> Only winner can submit during Final fix phase

- src/common/helper.js
- src/controllers/SubmissionController.js
- src/services/SubmissionService.js
This was in progress so reverting
> Revert "WIP: Check for Topcoder User role"

- src/common/helper.js
- src/controllers/SubmissionController.js
- src/services/SubmissionService.js
This PR is still in progress. Waiting for changes in Challenge API
Note: Test data need to be modified to validate different scenarios.
Design challenges seem to have phases like Checkpoint Screening, Checkpoint Review etc.. which need to be handled.
There are other complicated role checks too.
> Topcoder User role checks

- src/services/SubmissionService.js
> Add fileType while uploading submission in S3

- src/services/ReviewService.js
- src/services/ReviewSummationService.js
> Metadata support in Review and ReviewSummation

- src/routes/ReviewRoutes.js
- src/routes/ReviewSummationRoutes.js
- src/routes/SubmissionRoutes.js
> Fix scope issue w.r.t reading data

- docs/Submission API.postman_collection.json
- docs/swagger.yaml
- package-lock.json
- package.json
- src/common/helper.js
- src/controllers/SubmissionController.js
- src/routes/SubmissionRoutes.js
- src/services/SubmissionService.js
> Support downloading submissions

- scripts/data/Submissions.json
- src/bootstrap.js
- src/common/helper.js
> Sort submissions by created date

- docs/swagger.yaml
> Swagger fixes on metadata

- src/common/helper.js
- src/controllers/ReviewController.js
- src/services/ReviewService.js
Access check for GET /reviews/{:reviewId} end point.
> Access check for reviews

- src/common/helper.js
> Store original topic in payload when posting to aggregate topic

- src/services/SubmissionService.js
> Issue 120 - Prevent submission creation if file uploaded under wrong attribute

- docs/Submission API.postman_collection.json
- docs/swagger.yaml
- src/controllers/ArtifactController.js
- src/routes/SubmissionRoutes.js
- src/services/ArtifactService.js
> Support for deleting artifact

- config/default.js
- docs/Submission API.postman_collection.json
- docs/swagger.yaml
- package-lock.json
- package.json
- src/common/helper.js
- src/controllers/ArtifactController.js
- src/routes/SubmissionRoutes.js
- src/services/ArtifactService.js
- src/services/SubmissionService.js
includes
- bug fixes
- artifact deletion
- paging
> bringing master up to date w/ develop

- package-lock.json
- package.json
- src/services/ReviewService.js
> Fix lint errors and force pre commit lint checks

- src/services/ArtifactService.js
* Remove check for existence of artifact before uploading
* Overwrite existing artifact instead
Fix for https://github.com/topcoder-platform/submissions-api/issues/149
> Overwrite Existing Artifact

- src/routes/ReviewTypeRoutes.js
- test/e2e/ReviewTypeService.test.js
- test/unit/ReviewTypeService.test.js
> Allow Topcoder Users to read review types

- docs/Submission API.postman_collection.json
@cwdcwd Incoming fix for that postman param.
> Update the type param for POST

- src/routes/ReviewTypeRoutes.js
access: ['Topcoder User', 'Administrator', 'Copilot']
> Update GET for reviewTypes

- src/common/helper.js
> Hotfix 03 March2021 : shapeup pure v5 task 

- src/common/helper.js
> ignore appeals response phase for design track

- src/common/helper.js
> allow client managers to download submissions

- README.md
- app.js
- config/default.js
- docs/swagger.yaml
- local/docker-compose.yml
- package.json
- src/common/helper.js
- src/routes/ReviewRoutes.js
- src/routes/ReviewSummationRoutes.js
- src/routes/SubmissionRoutes.js
- src/services/ReviewService.js
- src/services/ReviewSummationService.js
- src/services/SubmissionService.js
Reverts topcoder-platform/submissions-api#279
> Issue Reviewer Role

- src/services/SubmissionService.js
* remove addition of duplicate legacyChallengeId in UpdateExpression path
> fix: challenge submission

- src/common/helper.js
update expression used to update record in dynamodb to remove duplicate legacyId clause
> fix: challenge patch failure

- src/common/helper.js
- src/controllers/SubmissionController.js
- src/routes/SubmissionRoutes.js
- src/services/SubmissionService.js
- test/unit/SubmissionService.test.js
https://topcoder.atlassian.net/browse/PROD-2786
> Allow submitters to delete their own submissions

- src/common/helper.js
* remove null reviews from submission.review
> fix: remove null reviews

- src/common/helper.js
* remove null reviews from submission.reivew
> fix: clean reviews

- .circleci/config.yml
- src/services/SubmissionService.js
https://topcoder.atlassian.net/browse/PROD-3146
> PROD - Strip out null reviews from submissions response (PROD-3146)

- src/common/informixHelper.js
Seeing some data in prod that doesn't match what we saw in dev.  Debugging now.
> HOTFIX - Debug logging to identify prod issues with certain data

- src/services/SubmissionService.js
Seeing some performance issues with Informix with the data coming in.
> HOTFIX - Add flag to load legacy data, with the default being not to

- src/routes/SubmissionRoutes.js
[…PS-268)](https://topcoder.atlassian.net/browse/PS-268)
> Add 'tgadmin' as an allowed role to list and get submission details 

- src/services/ReviewService.js
- src/services/ReviewSummationService.js
- src/services/SubmissionService.js
> Add 'tgadmin' to administrator auth checks for Topgear

- .circleci/config.yml
- package-lock.json
- src/common/helper.js
`X-Total-Pages` wasn't getting set properly in the headers, due to the change in total value from ES to OS.  This caused the relative scoring to break.  It was trying to pull all submissions, but not away of how many pages of submissions to pull (100 at a time) from the submissions API.
> HOTFIX for MM 159

- .circleci/config.yml
- src/common/helper.js
- src/constants/index.js
- src/controllers/ArtifactController.js
- src/services/ArtifactService.js
- src/services/HelperService.js
https://topcoder.atlassian.net/browse/PM-809
Adds authorization / permission checking for the artifacts endpoints (list & download). This should allow us to call the submissions API directly for listing artifacts and downloads.
> PM-809 artifact endpoint update

- src/services/ArtifactService.js
Issue with file names noted in MM 160
> Revert this change for MM bug
